### ISSUE TITLE
esp-mbedtls doesn't link with esp-wifi starting version 0.9.0

### ISSUE THREAD

**Issue by yanshay** [esp-rs/esp-mbedtls#47]
Getting the following errors with 0.9.0 while it is working with 0.8.0. See link errors below.

I noticed that `esp-mbedtls` is not treated as mainstream as other libs - it's not published on crates.io, not updated as part of the other libs release lifecycle so not to break, etc.
No complaints, but is it safe to rely on it? not that I have other options, but I just don't want to invest time and have it not work for me in the future since it is mandatory for me in current app until there is an alternative for `tls 1.2`, so maybe I'll switch to `esp-idf` instead with this application I'm writing.
 
If it is maintained and only late to get updates then worth adding in the README the versions of other libs it can work with until it get updates, especially with the frequent updates on other libs.

```
= note: /Users/my_user/.rustup/toolchains/esp/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /Users/my_user/ProgProj/ESP32/nfc-filament/target/xtensa-esp32s3-none-elf/release/build/esp-wifi-sys-4e0bc324e1feb971/out/libprintf.a(printf.c.obj): in function `snprintf':
          /COMPONENT_MAIN_DIR/printf/printf.c:884: multiple definition of `snprintf'; /Users/my_user/ProgProj/ESP32/nfc-filament/target/xtensa-esp32s3-none-elf/release/deps/libesp_mbedtls-79d800ed469e7bba.rlib(esp_mbedtls-79d800ed469e7bba.esp_mbedtls.d6a1500af71b5162-cgu.1.rcgu.o):/Users/my_user/.cargo/git/checkouts/esp-mbedtls-01aefbc1d66dfe86/7de5d0a/esp-mbedtls/src/compat/mod.rs:9: first defined here
          /Users/my_user/.rustup/toolchains/esp/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /Users/my_user/ProgProj/ESP32/nfc-filament/target/xtensa-esp32s3-none-elf/release/build/esp-wifi-sys-4e0bc324e1feb971/out/libprintf.a(printf.c.obj): in function `vsnprintf':
          /COMPONENT_MAIN_DIR/printf/printf.c:901: multiple definition of `vsnprintf'; /Users/my_user/ProgProj/ESP32/nfc-filament/target/xtensa-esp32s3-none-elf/release/deps/libesp_mbedtls-79d800ed469e7bba.rlib(esp_mbedtls-79d800ed469e7bba.esp_mbedtls.d6a1500af71b5162-cgu.1.rcgu.o):/Users/my_user/.cargo/git/checkouts/esp-mbedtls-01aefbc1d66dfe86/7de5d0a/esp-mbedtls/src/compat/mod.rs:14: first defined here
          collect2: error: ld returned 1 exit status
```

**Comment by AnthonyGrondin** [comment]
You're right, `esp-mbedtls` doesn't get as care and maintenance as the other mainstream crates. It is currently used as a big bandage, to cover a big hole of IoT functionality; TLS. That is, until pure Rust, better suited solutions come down the pipeline.

> but is it safe to rely on it?

It depends on how you define safe. This crate quite requires using fixed revisions and comes with breaking changes during every upgrade, because it is still in early stage.

I try as much as possible to keep it sync with new releases of `esp-hal`, but a new release of `esp-wifi` can bring breaking changes that break this crate. That being said, the situation will improve in the future because initially, we quite heavily depended on `esp-wifi`, for certain functionalities like string formatting and memory allocation. We can remove extra definitions and compat code for the next release

Unless more maintainers pay attention to this crate and roll new functionalities / improvements / upgrades, the state of this crate will depend on the current community effort.

If you're looking for a complete working option, I'd suggest to use `esp-idf`.

**Comment by AnthonyGrondin** [comment]
Can we close this now that #51 is merged?

**Comment by yanshay** [comment]
From my perspective yes, thanks.
