### ISSUE TITLE
Example builds fail with edge-http 0.5.1 but compile with 0.6.1

### ISSUE THREAD

**Issue by burumdev** [esp-rs/esp-mbedtls#89]
While running the examples with command:
`SSID=<your_ssid> PASSWORD=<your_password> cargo +nightly run --release --example async_client -F esp32c3,examples-async --target riscv32imc-unknown-none-elf`

I get the compilation error:

```
   Compiling edge-http v0.5.1
error[E0308]: mismatched types
   --> /home/baris/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/edge-http-0.5.1/src/io/server.rs:703:65
    |
677 |                 .push(async move {
    |                       ---------- the found `async` block
...
703 |         let (result, _) = embassy_futures::select::select_slice(&mut tasks).await;
    |                           ------------------------------------- ^^^^^^^^^^ expected `Pin<&mut [_]>`, found `&mut Vec<..., P>`
    |                           |
    |                           arguments to this function are incorrect
    |
    = note:         expected struct `Pin<&mut [_]>`
            found mutable reference `&mut Vec<{async block@/home/baris/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/edge-http-0.5.1/src/io/server.rs:677:23: 677:33}, P>`
note: function defined here
   --> /home/baris/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/embassy-futures-0.1.2/src/select.rs:523:8
    |
523 | pub fn select_slice<'a, Fut: Future>(slice: Pin<&'a mut [Fut]>) -> SelectSlice<'a, Fut> {
    |        ^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `edge-http` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

Upgrading edge-http to 0.6.1 version in Cargo.toml seems to fix the issue:
`edge-http = { version = "0.6.1", optional = true }`

**Comment by AnthonyGrondin** [comment]
We just need to bump `edge-http`

See: https://github.com/sysgrok/edge-net/issues/74
